In [1]:
import folium
import numpy as np
import pandas as pd
from folium.plugins import HeatMap
from folium import plugins
import ipywidgets as widgets
from IPython.display import display, clear_output
import matplotlib.colors as mcolors
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import calendar
from IPython.display import display, Markdown
from pathlib import Path
import plotly.colors
import random

In [ ]:
df_Large=pd.read_csv("data/fullWithLocations_FINAL_large.csv",index_col=False)

In [3]:
display(df_Large.columns.sort_values())
display(df_Small.columns.sort_values())

Index(['City', 'DOY', 'Date', 'EVLAND', 'GOV', 'GWETPROF', 'GWETROOT',
       'GWETTOP', 'LAT', 'LON', 'Month', 'PRECSNO', 'PRECTOTCORR', 'QV2M',
       'RH2M', 'RHOA', 'T10M', 'T10M_MAX', 'T10M_MIN', 'T2M', 'T2M_MAX',
       'T2M_MIN', 'TO3', 'TS', 'TSOIL1', 'TSOIL2', 'TSOIL3', 'TSOIL4',
       'TSOIL5', 'TSOIL6', 'TS_MAX', 'TS_MIN', 'Unnamed: 0', 'WD2M', 'WD50M',
       'WS2M', 'WS2M_MAX', 'WS2M_MIN', 'WS50M', 'WS50M_MAX', 'WS50M_MIN',
       'Week', 'YEAR', 'Z0M'],
      dtype='object')

Index(['AIRMASS', 'ALLSKY_SFC_SW_DWN', 'ALLSKY_SFC_UVA', 'ALLSKY_SFC_UVB',
       'ALLSKY_SFC_UV_INDEX', 'CLOUD_AMT', 'CLOUD_AMT_DAY', 'CLOUD_AMT_NIGHT',
       'CLRSKY_DAYS', 'City', 'DOY', 'Date', 'GOV', 'LAT', 'LON',
       'MIDDAY_INSOL', 'Month', 'PSH', 'PW', 'Unnamed: 0', 'Week', 'YEAR'],
      dtype='object')

In [ ]:
Group_large=['EVLAND', 'GWETPROF',
       'GWETROOT', 'GWETTOP', 'PRECSNO', 'PRECTOTCORR', 'QV2M', 'RH2M', 'RHOA','T10M', 'T10M_MAX', 'T10M_MIN', 'T2M', 'T2M_MAX', 'T2M_MIN', 'TO3',
       'TS', 'TSOIL1', 'TSOIL2', 'TSOIL3', 'TSOIL4', 'TSOIL5', 'TSOIL6','TS_MAX', 'TS_MIN', 'WD2M', 'WD50M', 'WS2M', 'WS2M_MAX', 'WS2M_MIN',
       'WS50M', 'WS50M_MAX', 'WS50M_MIN', 'Z0M']

Group_small=['AIRMASS', 'ALLSKY_SFC_SW_DWN', 'ALLSKY_SFC_UVA', 'ALLSKY_SFC_UVB',
       'ALLSKY_SFC_UV_INDEX', 'CLOUD_AMT', 'CLOUD_AMT_DAY', 'CLOUD_AMT_NIGHT',
       'CLRSKY_DAYS', 'City', 'DOY', 'Date', 
       'MIDDAY_INSOL', 'PSH', 'PW']

df_Mapped=pd.read_csv("data/dataMapping.csv")

In [5]:
display(df_Large[Group_large].describe())
display(df_Large[Group_large].info())

,EVLAND,GWETPROF,GWETROOT,GWETTOP,PRECSNO,PRECTOTCORR,QV2M,RH2M,RHOA,T10M,...,TS_MIN,WD2M,WD50M,WS2M,WS2M_MAX,WS2M_MIN,WS50M,WS50M_MAX,WS50M_MIN,Z0M
count,503976.000000,608286.000000,608286.000000,608286.000000,608286.000000,608286.000000,608286.000000,608286.000000,608286.000000,608286.000000,...,608286.000000,608286.000000,608286.000000,608286.000000,608286.000000,608286.000000,608286.000000,608286.000000,608286.000000,608286.000000
mean,0.120438,0.290890,0.288736,0.123217,0.000022,0.121952,6.364653,40.216038,1.150884,22.971601,...,14.794899,219.334542,212.851821,3.192033,4.984569,1.628083,6.126163,8.450234,3.700114,0.012140
std,0.282042,0.095294,0.095300,0.107123,0.003760,2.035040,2.623961,17.779893,0.041842,7.491629,...,7.384503,141.827236,144.899527,1.068664,1.379426,0.861024,1.686289,1.742654,1.977856,0.006852
min,0.000000,0.090000,0.090000,0.030000,0.000000,0.000000,0.900000,5.180000,1.020000,2.000000,...,-6.260000,0.000000,0.000000,0.490000,0.860000,0.000000,0.760000,1.370000,0.000000,0.000000
25%,0.000000,0.200000,0.200000,0.060000,0.000000,0.000000,4.500000,24.850000,1.120000,16.420000,...,8.300000,40.700000,34.000000,2.410000,4.040000,1.070000,4.960000,7.390000,2.150000,0.010000
50%,0.010000,0.330000,0.320000,0.080000,0.000000,0.000000,5.920000,38.220000,1.150000,23.620000,...,15.510000,304.900000,301.500000,3.110000,4.960000,1.490000,6.140000,8.530000,3.680000,0.010000
75%,0.070000,0.340000,0.340000,0.140000,0.000000,0.000000,7.680000,54.380000,1.180000,29.400000,...,21.160000,339.900000,340.400000,3.880000,5.860000,2.080000,7.290000,9.530000,5.130000,0.010000
max,4.120000,0.750000,0.770000,0.850000,1.510000,506.620000,23.750000,93.620000,1.270000,40.050000,...,33.130000,360.000000,360.000000,10.600000,15.480000,9.090000,16.570000,23.520000,13.270000,0.070000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 608286 entries, 0 to 608285
Data columns (total 34 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   EVLAND       503976 non-null  float64
 1   GWETPROF     608286 non-null  float64
 2   GWETROOT     608286 non-null  float64
 3   GWETTOP      608286 non-null  float64
 4   PRECSNO      608286 non-null  float64
 5   PRECTOTCORR  608286 non-null  float64
 6   QV2M         608286 non-null  float64
 7   RH2M         608286 non-null  float64
 8   RHOA         608286 non-null  float64
 9   T10M         608286 non-null  float64
 10  T10M_MAX     608286 non-null  float64
 11  T10M_MIN     608286 non-null  float64
 12  T2M          608286 non-null  float64
 13  T2M_MAX      608286 non-null  float64
 14  T2M_MIN      608286 non-null  float64
 15  TO3          608286 non-null  float64
 16  TS           608286 non-null  float64
 17  TSOIL1       608286 non-null  float64
 18  TSOIL2       608286 non-null  float64
 19  TSOIL3       608286 non-null  float64
 20  TSOIL4       608286 non-null  float64
 21  TSOIL5       608286 non-null  float64
 22  TSOIL6       608286 non-null  float64
 23  TS_MAX       608286 non-null  float64
 24  TS_MIN       608286 non-null  float64
 25  WD2M         608286 non-null  float64
 26  WD50M        608286 non-null  float64
 27  WS2M         608286 non-null  float64
 28  WS2M_MAX     608286 non-null  float64
 29  WS2M_MIN     608286 non-null  float64
 30  WS50M        608286 non-null  float64
 31  WS50M_MAX    608286 non-null  float64
 32  WS50M_MIN    608286 non-null  float64
 33  Z0M          608286 non-null  float64
dtypes: float64(34)
memory usage: 157.8 MB

None

In [6]:
display(df_Small[Group_small].describe())
display(df_Small[Group_small].info())

,AIRMASS,ALLSKY_SFC_SW_DWN,ALLSKY_SFC_UVA,ALLSKY_SFC_UVB,ALLSKY_SFC_UV_INDEX,CLOUD_AMT,CLOUD_AMT_DAY,CLOUD_AMT_NIGHT,CLRSKY_DAYS,DOY,MIDDAY_INSOL,PSH,PW
count,208240.000000,208240.000000,208240.00000,208240.000000,208240.000000,208240.000000,208240.000000,208240.000000,208240.000000,208240.000000,208240.000000,208240.000000,208240.000000
mean,-66.241524,-48.407918,-68.52901,-69.698267,-67.885213,-53.830662,-54.601540,-52.949911,-69.288451,183.166971,1.601164,-69.217760,-68.342561
std,255.510881,260.451942,254.88328,254.562773,255.060600,259.561034,259.437237,259.910897,254.675488,105.463034,274.405508,254.694431,254.934813
min,-999.000000,-999.000000,-999.00000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,1.000000,-999.000000,-999.000000,-999.000000
25%,3.010000,17.000000,0.93000,0.020000,1.130000,2.610000,1.680000,2.350000,0.000000,92.000000,63.690000,0.410000,0.930000
50%,3.590000,23.180000,1.30000,0.030000,1.920000,9.560000,7.140000,9.420000,0.000000,183.000000,79.110000,0.560000,1.360000
75%,4.200000,27.870000,1.59000,0.040000,2.610000,20.720000,20.720000,22.380000,1.000000,274.250000,87.750000,0.670000,1.850000
max,6.670000,32.210000,1.89000,0.060000,7.990000,99.880000,100.000000,100.000000,1.000000,366.000000,98.250000,0.770000,5.020000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208240 entries, 0 to 208239
Data columns (total 15 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   AIRMASS              208240 non-null  float64
 1   ALLSKY_SFC_SW_DWN    208240 non-null  float64
 2   ALLSKY_SFC_UVA       208240 non-null  float64
 3   ALLSKY_SFC_UVB       208240 non-null  float64
 4   ALLSKY_SFC_UV_INDEX  208240 non-null  float64
 5   CLOUD_AMT            208240 non-null  float64
 6   CLOUD_AMT_DAY        208240 non-null  float64
 7   CLOUD_AMT_NIGHT      208240 non-null  float64
 8   CLRSKY_DAYS          208240 non-null  float64
 9   City                 208240 non-null  object
 10  DOY                  208240 non-null  int64
 11  Date                 208240 non-null  object
 12  MIDDAY_INSOL         208240 non-null  float64
 13  PSH                  208240 non-null  float64
 14  PW                   208240 non-null  float64
dtypes: float64(12), int64(1), object(2)
memory usage: 23.8+ MB

None

In [7]:
df_Large['Month_Name'] = df_Large['Month'].apply(lambda x: calendar.month_abbr[x]) 
df_Small['Month_Name'] = df_Small['Month'].apply(lambda x: calendar.month_abbr[x])

In [8]:
attribute_options = df_Mapped["Code"]
attribute_selector = widgets.Dropdown(
    options=attribute_options,
    value="PRECTOTCORR",
    description="Attribute:"
)
display(attribute_selector)

Dropdown(description='Attribute:', index=29, options=('WD2M', 'WD50M', 'WS2M', 'WS2M_MAX', 'WS2M_MIN', 'WS50M'…

In [19]:
display(attribute_selector.value)

'T2M'

In [20]:
attribute=attribute_selector.value
Att_Name = df_Mapped.loc[df_Mapped["Code"] == attribute, "Name"].iloc[0]
color_palette = plotly.colors.qualitative.Safe  
color_UN = random.choice(color_palette)
base_dir = Path(f"resources/{attribute}")
base_dir.mkdir(parents=True, exist_ok=True)

In [21]:

Total_info = pd.DataFrame(columns=["Attribute", "NULLs_Count", "Zeros_Percentage"])
for Attribute in Group_large + Group_small:
    if Attribute in df_Large:
        new_row = pd.DataFrame([{
            "Attribute": Attribute,
            "NULLs_Count": df_Large[Attribute].isnull().sum(),
            "Zeros_Percentage": (df_Large[Attribute] == 0).mean() * 100  
        }])
        Total_info = pd.concat([Total_info, new_row], ignore_index=True)

    elif Attribute in df_Small:
        new_row = pd.DataFrame([{
            "Attribute": Attribute,
            "NULLs_Count": df_Small[Attribute].isnull().sum(),
            "Zeros_Percentage": (df_Small[Attribute] == 0).mean() * 100  
        }])
        Total_info = pd.concat([Total_info, new_row], ignore_index=True)

display(Total_info.sort_values(by="Zeros_Percentage"))

C:\Users\ahmed\AppData\Local\Temp\ipykernel_23304\1180488115.py:9: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

              Attribute NULLs_Count  Zeros_Percentage
1              GWETPROF           0          0.000000
2              GWETROOT           0          0.000000
3               GWETTOP           0          0.000000
7                  RH2M           0          0.000000
6                  QV2M           0          0.000000
10             T10M_MAX           0          0.000000
9                  T10M           0          0.000000
8                  RHOA           0          0.000000
15                  TO3           0          0.000000
13              T2M_MAX           0          0.000000
12                  T2M           0          0.000000
20               TSOIL4           0          0.000000
19               TSOIL3           0          0.000000
18               TSOIL2           0          0.000000
17               TSOIL1           0          0.000000
16                   TS           0          0.000000
27                 WS2M           0          0.000000
31            WS50M_MAX           0          0.000000
30                WS50M           0          0.000000
28             WS2M_MAX           0          0.000000
22               TSOIL6           0          0.000000
21               TSOIL5           0          0.000000
23               TS_MAX           0          0.000000
48                   PW           0          0.000000
43                 City           0          0.000000
46         MIDDAY_INSOL           0          0.000000
45                 Date           0          0.000000
44                  DOY           0          0.000000
47                  PSH           0          0.000000
36       ALLSKY_SFC_UVA           0          0.000000
34              AIRMASS           0          0.000000
35    ALLSKY_SFC_SW_DWN           0          0.000000
11             T10M_MIN           0          0.000164
38  ALLSKY_SFC_UV_INDEX           0          0.000480
32            WS50M_MIN           0          0.000493
14              T2M_MIN           0          0.001315
29             WS2M_MIN           0          0.001644
24               TS_MIN           0          0.005096
37       ALLSKY_SFC_UVB           0          0.022570
25                 WD2M           0          0.051949
26                WD50M           0          0.060005
41      CLOUD_AMT_NIGHT           0          1.975125
39            CLOUD_AMT           0          2.027949
40        CLOUD_AMT_DAY           0          2.471667
33                  Z0M           0          3.171206
0                EVLAND      104310         32.719149
42          CLRSKY_DAYS           0         48.918075
5           PRECTOTCORR           0         87.866398
4               PRECSNO           0         99.981423

In [22]:
if attribute in Group_large:
    df=df_Large.copy()
else :
    df =df_Small.copy()

In [23]:
display(Markdown(f"<h1 style='color:{color_UN}; font-weight:bold; font-size: 40px;'>Histogram FOR {Att_Name} PER MONTH</h1>"))

<h1 style='color:rgb(170, 68, 153); font-weight:bold; font-size: 40px;'>Histogram FOR Temperature at 2 Meters PER MONTH</h1>

In [24]:
for YEAR in df["YEAR"].unique():
    dff = df[df["YEAR"] == YEAR]  

    fig = px.histogram(dff, 
                       x=attribute, 
                       nbins=50,#50  
                       facet_col="Month_Name", 
                       facet_col_wrap=5,  # Wrap into rows of 3 columns
                       title=f"{Att_Name} for YEAR={YEAR}",  
                       labels={f"{Att_Name}": f"{Att_Name}", "count": "Frequency"},
                       color_discrete_sequence=["royalblue"],  
                       opacity=0.75,  
                      )

    fig.update_layout(
        template="plotly_white",
        xaxis_title=Att_Name,
        yaxis_title="Frequency",
        hovermode="x unified"
    )

    fig.show()
    fig.write_html(f"resources/{attribute}/histogram_{Att_Name}_byMonth_Year{YEAR}.html")

In [15]:
display(Markdown(f"<h1 style='color:{color_UN}; font-weight:bold; font-size: 40px;'>Pie Chart FOR {Att_Name} PER MONTH</h1>"))

<h1 style='color:rgb(68, 170, 153); font-weight:bold; font-size: 40px;'>Pie Chart FOR Precipitation Corrected PER MONTH</h1>

In [16]:
df_avg = df.groupby(['YEAR', 'Month_Name'], as_index=False)[attribute].mean()

for year in df_avg["YEAR"].unique():
    year_data = df_avg[df_avg['YEAR'] == year]
    
    fig = px.pie(year_data, 
                names='Month_Name',  
                values=attribute,  
                title=f"Average {Att_Name} per Month in {year}",
                hole=0.3)  
    fig.update_traces(textinfo='label+percent')

    fig.show()

In [17]:
display(Markdown(f"<h1 style='color:{color_UN}; font-weight:bold; font-size: 40px;'>BAR GRAPH FOR {Att_Name} PER MONTH</h1>"))

<h1 style='color:rgb(68, 170, 153); font-weight:bold; font-size: 40px;'>BAR GRAPH FOR Precipitation Corrected PER MONTH</h1>

In [18]:
for YEAR in df["YEAR"].unique():
    dff = df[df["YEAR"] == YEAR]
    all_months = pd.DataFrame({"Month": range(1, 13)}) 
    month_stats = dff.groupby("Month")[attribute].agg(["min", "max", "mean"]).reset_index()
    month_stats = all_months.merge(month_stats, on="Month", how="left").fillna(0)  

    month_stats_melted = month_stats.melt(id_vars="Month", var_name="Statistic", value_name=attribute)

    fig = px.bar(month_stats_melted, 
                x="Month", 
                y=attribute, 
                text=attribute,  
                title=f"Min, Max, and Mean {Att_Name} per Month for {YEAR}",
                labels={f"{attribute}": f"{Att_Name}", "Month": "Month"},
                color="Statistic",
                barmode="group",   
                color_discrete_map={"min": "blue", "max": "red", "mean": "green"}  
                )

    for trace in fig.data:
        if isinstance(trace, go.Bar):
            trace.texttemplate = "%{y:.2f}"
            trace.textposition = "outside"

    for stat, color in zip(["min", "max", "mean"], ["blue", "red", "green"]):
        fig.add_trace(go.Scatter(
            x=month_stats["Month"], 
            y=month_stats[stat], 
            mode="lines+markers", 
            name=f"{stat} Trend",
            line=dict(color=color, width=2, dash="dash"),
            marker=dict(size=6)
        ))

    fig.update_layout(
        xaxis=dict(tickmode="linear", dtick=1, tickangle=0), 
        template="plotly_white",
        hovermode="x",
        yaxis_title=attribute
    )
    
    fig.show()

    fig.write_html(f"resources/{attribute}/months_MinMaxMean_Barplot_Year{YEAR}.html")

KeyboardInterrupt:

In [ ]:
display(Markdown(f"<h1 style='color:{color_UN}; font-weight:bold; font-size: 40px;'>BAR GRAPH FOR {Att_Name} PER CITY</h1>"))

<h1 style='color:rgb(170, 68, 153); font-weight:bold; font-size: 40px;'>BAR GRAPH FOR Precipitation Corrected PER CITY</h1>

In [ ]:
for YEAR in df["YEAR"].unique():
    
    city_stats = df[df["YEAR"] == YEAR].groupby("City")[attribute].agg(["min", "max", "mean"]).reset_index()

    city_stats_melted = city_stats.melt(id_vars="City", var_name="Statistic", value_name=attribute)

    fig = px.bar(city_stats_melted, 
                 x="City", 
                 y=attribute, 
                 color="Statistic", 
                 barmode="group",
                 title=f"Min, Max, and Mean {Att_Name} per City for {YEAR}",
                 labels={f"{attribute}": f"{Att_Name}", "City": "City"},
                 color_discrete_map={"min": "#1f77b4", "max": "#ff7f0e", "mean": "#2ca02c"}  
                )

    for trace in fig.data:
        if isinstance(trace, go.Bar):
            trace.texttemplate = "%{y:.2f}"
            trace.textposition = "outside"

    for stat, color in zip(["min", "max", "mean"], ["#1f77b4", "#ff7f0e", "#2ca02c"]):
        fig.add_trace(go.Scatter(
            x=city_stats["City"], 
            y=city_stats[stat], 
            mode="lines+markers", 
            name=f"{stat} Trend",
            line=dict(color=color, width=2, dash="dash"),
            marker=dict(size=6)
        ))
    fig.update_layout(
        legend_title_text="Statistic",
        xaxis_title="City",
        yaxis_title=Att_Name,
        xaxis=dict(tickangle=270),
        template="plotly_white",
        hovermode="x"
    )

    fig.show()
    fig.write_html(f"resources/{attribute}/Cities_MinMaxMean_Barplot_Year{YEAR}.html")

In [ ]:
display(Markdown(f"<h1 style='color:{color_UN}; font-weight:bold; font-size: 40px;'>Top valued points and dates {Att_Name}</h1>"))

<h1 style='color:rgb(170, 68, 153); font-weight:bold; font-size: 40px;'>Top valued points and dates Precipitation Corrected</h1>

In [ ]:
top_10_points = df.nlargest(10, attribute).copy() 
date_counts = top_10_points["Date"].value_counts()
city_counts = top_10_points["City"].value_counts()
top_10_points["Count_Dates"] = top_10_points["Date"].map(date_counts)
top_10_points["Count_Cities"] = top_10_points["City"].map(city_counts)
display(top_10_points[["City","Count_Cities", attribute, "Date", "Count_Dates"]])

,City,Count_Cities,PRECTOTCORR,Date,Count_Dates
223273,Burj al-'Arab,1,506.62,2021-03-19,10
223257,Al-Hammam,2,380.73,2021-03-19,10
223271,Marsa Matruh,2,358.30,2021-03-19,10
223258,Al-Hammam,2,344.26,2021-03-19,10
223272,Ad-Dab'ah,2,273.81,2021-03-19,10
223194,Unorganized in Al Jizah,1,270.05,2021-03-19,10
223255,Marsa Matruh,2,243.07,2021-03-19,10
223256,Ad-Dab'ah,2,242.32,2021-03-19,10
223193,Siwa,2,229.13,2021-03-19,10
223192,Siwa,2,201.23,2021-03-19,10